using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEditor.Build;
using UnityEngine;

public class CameraMovement : MonoBehaviour
{

    public Controller controls; // Instance of the Controlle class generated by the Input System
    public GameObject player; // Reference to the player's GameObject
    public Vector2 cameraInput; // Vector2 to store camera input values
    public GameObject Pivot; // Reference to the pivot GameObject for vertical rotation
    public float sensitivity = 100f; // Sensitivity of the camera movement
    public float xRotation = 0f; // Variable to track the vertical rotation of the camera

    public void Awake()
    {
        controls = new Controller(); // Instantiate the Controlle input actions
    }
    private void OnEnable()
    {
        controls.Enable(); // Enable the input action map
        controls.Player.Look.performed += ctx => cameraInput = ctx.ReadValue<Vector2>(); //Whenever the Look event is performed, store Look value inside ctx and assign ctx value to cameraInput
        controls.Player.Look.canceled += ctx => cameraInput = Vector2.zero; //When the Look event is canceled, set cameraInput to zero
    }
    private void OnDisable()
    {
        controls.Disable(); // Disable the input action map
    }

    // Update is called once per frame
    void Update()
    {
        CameraMove(); // Call the CameraMove method every frame
    }
    public void CameraMove() // Method to handle camera movement
    {
        Vector2 Look = cameraInput * sensitivity * Time.deltaTime; // Scale the camera input by sensitivity and deltaTime
        xRotation -= Look.y; // Invert the Y-axis for vertical rotation

        xRotation = Mathf.Clamp(xRotation, -90f, 90f); // Returns A number between -90 and 90

        Pivot.transform.localRotation = Quaternion.Euler(xRotation, 0, 0); // Apply vertical rotation to the pivot  

        player.transform.Rotate(Vector3.up, Look.x);// Rotate the player body horizontally based on Look.x
    }
}
